krbe_file_manager:
    quota_max: -1  # -1 pour illimité, sinon en octets
    max_file_size: 10485760  # 10MB
    allowed_mime_types:
        - image/jpeg
        - image/png
        - image/gif
        - image/webp
        - image/svg+xml
        - application/pdf
        - application/msword
        - application/vnd.openxmlformats-officedocument.wordprocessingml.document
        - application/vnd.ms-excel
        - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
        - text/plain
        - text/csv
        - application/json
        - application/xml
        - text/xml
    image_processing:
        compression_enabled: true
        compression_quality: 80
        create_webp: true
        keep_original: true
    storage:
        type: local
        local:
            path: '%kernel.project_dir%/public/cdn'
        s3:
            key: ~
            secret: ~
            region: ~
            bucket: ~
            path: '' 